language: python
python:
  - "3.6"
  - "3.7"

install:
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - export PATH=$PATH:~/.poetry/bin
  - make install

script:
  - make ci

deploy:
  - provider: script
    script: poetry publish --build --username="$PYPI_USERNAME" --password="$PYPI_PASSWORD"
    on:
      tags: true
